trigger:
    branches:
      include:
          - develop
    paths:
      exclude:
          - '*.md'
          - '*.txt'
          - '.vscode/*'

pool:
    vmImage: 'ubuntu-latest'

stages:
  - template: read-project-info.stage.yml
  - stage: Develop
    displayName: Develop
    jobs:
        - job: Next Build
          steps:
              - task: UseNode@1
                inputs:
                    version: '18.x'
                displayName: 'Use Node.js 18.x'

              - script: |
                  npm install
                  npm run build
                displayName: 'Building App'

              - task: ArchiveFiles@1
                inputs:
                    rootFolder: '$(System.DefaultWorkingDirectory)'
                    includeRootFolder: false

              - task: CopyFiles@2
                displayName: 'Copy File to: $(TargetFolder)'
                inputs:
                  SourceFolder: '$(Build.ArtifactStagingDirectory)'
                  Contents: '$(Build.BuildId).zip'
                  TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

              - task: PublishBuildArtifacts@1
                displayName: 'Publish Artifact'
                inputs:
                  PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
        - job: Deploy
          - deployment: Deploy
            displayName: Deploying
            environment: 'develop'
            steps:
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'devops-landing-page'
                  resourceGroupName: 'rg_dev_rutia_landing' 
                  appType: 'webAppLinux'
                  appName: 'rutia-dev-landing-page'
                  deployToSlotOrASE: true
                  slotName: Production
                  package: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
                displayName: Deploy to Azure Web App